name:                kafka-pipes
version:             0.1.0.0
github:              "kaffepanna/kafka-pipes"
license:             BSD3
author:              "Patrik Pettersson"
maintainer:          "pettersson.pa@gmail.com"
copyright:           "2020 Patrik Pettersson"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/kaffepanna/kafka-pipes#readme>

dependencies:
- base >= 4.7 && < 5
- pipes
- pipes-safe
- exceptions
- hw-kafka-client
- bytestring
library:
  source-dirs: src


tests:
  kafka-pipes-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - kafka-pipes
