name: Haskell CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup stack
      uses: mstksg/setup-stack@v1
    - uses: actions/cahe@v1
      name: Cache stack
      with:
        path: ${HOME}/.stack
        key: ${{ os.runner }}-stack
    - name: Install dependencies
      run: |
        sudo apt-get install -y librdkafka-dev
        stack --no-terminal --install-ghc setup
    - name: Build
      run: |
        stack --no-terminal build
    - name: Run tests
      run: |
        stack --no-terminal test
